### ISSUE TITLE
Buggy behaviour when changing reselts-per-page

### ISSUE THREAD

**Issue by gpetrioli** [xargr/eprofit#1]
In the demo, when you select 5 results per page and then go to the last page of the results and then change the results per page back to 20 you will get in a wrong state.

You will be at page 20 out of 5 available (first issue)
And if you navigate to previous page you will go to 19 of 5 etc. So you need to navigate all the empty pages that were calculated when you had 5 results per page.

Looks like you need to recalculate and modify the current page after changing the results per page value.

**Comment by xargr** [comment]
@gpetrioli thanks a lot for your feedback!! I fix it with reset the data on every page per data changes.
